### ISSUE TITLE
HTML Element not work in r293

### ISSUE THREAD

**Issue by XIMIKATIK** [el3um4s/construct-plugins-and-addons#14]
Hello does not work in r293, can we count on a fix?
I get such errors:

Uncaught TypeError: globalThis.createElement is not a function
    at 0218044d-ca6a-4cf8-bf35-aa520bdfe716:235:26
    at 0218044d-ca6a-4cf8-bf35-aa520bdfe716:2021:3
 

Uncaught (in promise) ReferenceError: Dom is not defined
    at StraniAnelli_HTMLElementInstance.CreateElement (4d4eedc5-3522-4b02-8155-bd163c6a49fa:843:21)
    at new StraniAnelli_HTMLElementInstance (4d4eedc5-3522-4b02-8155-bd163c6a49fa:203:12)
    at Function.New (jsutil.js:15:47)
    at Instance._CreateSdkInstance (instance.js:7:189)
    at C3Runtime.CreateInstanceFromData (runtime.js:57:146)
    at Layer.CreateInitialInstances (layer.js:10:40)
    at Layout._CreateInitialInstances (layout.js:29:407)
    at Layout._StartRunning (layout.js:25:359)
    at C3Runtime.Start (runtime.js:39:417)
    at async C3Runtime.Init (runtime.js:24:161)

**Comment by el3um4s** [comment]
>Hello does not work in r293, can we count on a fix?

No.

With the latest stable version of Construct HTML Element is an official plugin. I recommend using the one released by Construct instead of mine.

**Comment by XIMIKATIK** [comment]
@[el3um4s](https://github.com/el3um4s) My app is completely built on your plugin, I can't rewrite it from scratch...
